[tool.poetry]
name = "coffee-classification"
version = "0.1.0"
description = ""
authors = ["William <william1504@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
opencv-python = "^4.5.4"
tensorflow = "^2.7.0"
matplotlib = "^3.4.3"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
